package com.meteoradesigner.model;

public enum InternalExecutionState {
    INTERNAL_EXECUTION_STATE_DISABLED,
    INTERNAL_EXECUTION_STATE_ENABLED,
    INTERNAL_EXECUTION_STATE_ACTIVE,
    INTERNAL_EXECUTION_STATE_FROZEN,
    INTERNAL_EXECUTION_STATE_FROZEN_WITH_FORCIBLY_UNLOCKED_RELATIVES,
    INTERNAL_EXECUTION_STATE_FROZEN_WITH_FORCIBLY_UNLOCKED_RELATIVES_BY,
    INTERNAL_EXECUTION_STATE_COMPLETED,
    INTERNAL_EXECUTION_STATE_TENTATIVE,
}
