package com.meteoradesigner.model;

public enum SelfCompletionState {
    SELF_COMPLETION_STATE_SERIAL,
    SELF_COMPLETION_STATE_CONCURRENT,
    SELF_COMPLETION_STATE_PARALLEL,
    SELF_COMPLETION_STATE_MONO,
    SELF_COMPLETION_STATE_SERIAL_STRICT,
    SELF_COMPLETION_STATE_CONCURRENT_STRICT,
    SELF_COMPLETION_STATE_PARALLEL_STRICT,
    SELF_COMPLETION_STATE_MONO_STRICT,
}
